from __future__ import annotations

from typing import Protocol

from app.core.models import AccountInfo, Candle, OrderRequest, OrderResult, Position


class ExchangeClient(Protocol):
    async def get_candles(self, symbol: str, timeframe: str, limit: int) -> list[Candle]: ...
    async def get_ticker(self, symbol: str) -> float: ...
    async def get_open_position(self, symbol: str) -> Position | None: ...
    async def get_account_info(self) -> AccountInfo: ...
    async def place_order(self, request: OrderRequest) -> OrderResult: ...
    async def close_position(self, symbol: str) -> OrderResult: ...
    async def cancel_open_orders(self, symbol: str) -> list[OrderResult]: ...
